
export const depto = [
    { label: "SELECCIONE DEPARTAMENTO", value: 0 },
    { label: "ANTIOQUIA", value: 5 },
    { label: "ATLANTICO", value: 8 },
    { label: "BOGOTA D.C.", value: 11 },
    { label: "VALLE DEL CAUCA", value: 76 },
    { label: "CUNDINAMARCA", value: 25 },
    { label: "MAGDALENA", value: 47 },
    { label: "No Aplica", value: 7 },
];

export const tipodocumento = [
    { label: "TIPO DOCUMENTO", value: 0 },
    { label: "Cedula de Ciudadanía", value: 1 },
    { label: "Cedula de Extranjería", value: 2 },
    { label: "Pasaporte", value: 3 },
    { label: "Número de Identificación Tributaria", value: 4 }
];

export const paises = [
    {value: 0, label: "SELECCIONE PAIS", codigopais: "0"},
    {value: 63, label: "ARGENTINA", codigopais: "AR"},
    {value: 97, label: "BOLIVIA", codigopais: "BO"},
    {value: 105, label: "BRASIL", codigopais: "BR"},
    {value: 149, label: "CANADA", codigopais: "CA"},
    {value: 169, label: "COLOMBIA", codigopais: "CO"},
    {value: 196, label: "COSTA RICA", codigopais: "CR"},
    {value: 211, label: "CHILE", codigopais: "CH"},
    {value: 239, label: "ECUADOR", codigopais: "EC"},
    {value: 245, label: "ESPAÑA", codigopais: "ES"},
    {value: 249, label: "ESTADOS UNIDOS", codigopais: "US"},
    {value: 493, label: "MEXICO", codigopais: "ME"},
    {value: 580, label: "PANAMA", codigopais: "PA"},
    {value: 589, label: "PERU", codigopais: "PE"},
    {value: 850, label: "VENEZUELA", codigopais: "VE"}
];

export const ciudad = [
    {value:0,label:"SELECCIONE CIUDAD",iddepto:5,nombredepto:""},
    {value:5120,label:"CACERES",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5154,label:"CAUCASIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5250,label:"EL BAGRE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5495,label:"NECHÍ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5790,label:"TARAZA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5895,label:"ZARAGOZA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5142,label:"CARACOLÍ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5425,label:"MACEO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5579,label:"PUERTO BERRiO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5585,label:"PUERTO NARE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5591,label:"PUERTO TRIUNFO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5893,label:"YONDÓ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5031,label:"AMALFI",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5040,label:"ANORÍ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5190,label:"CISNEROS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5604,label:"REMEDIOS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5670,label:"SAN ROQUE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5690,label:"SANTO DOMINGO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5736,label:"SEGOVIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5858,label:"VEGACHÍ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5885,label:"YALÍ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5890,label:"YOLOMBÓ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5038,label:"ANGOSTURA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5086,label:"BELMIRA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5107,label:"BRICEÑO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5134,label:"CAMPAMENTO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5150,label:"CAROLINA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5237,label:"DON MATiAS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5264,label:"ENTRERRIOS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5310,label:"GÓMEZ PLATA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5315,label:"GUADALUPE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5361,label:"ITUANGO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5647,label:"SAN ANDRÉS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5658,label:"SAN JOSÉ DE LA MONTAÑA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5664,label:"SAN PEDRO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5686,label:"SANTA ROSA de osos",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5819,label:"TOLEDO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5854,label:"VALDIVIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5887,label:"YARUMAL",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5004,label:"ABRIAQUÍ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5044,label:"ANZA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5059,label:"ARMENIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5113,label:"BURITICA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5138,label:"CAÑASGORDAS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5234,label:"DABEIBA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5240,label:"EBÉJICO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5284,label:"FRONTINO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5306,label:"GIRALDO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5347,label:"HELICONIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5411,label:"LIBORINA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5501,label:"OLAYA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5543,label:"PEQUE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5628,label:"SABANALARGA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5656,label:"SAN JERÓNIMO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5042,label:"SANTAFÉ DE ANTIOQUIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5761,label:"SOPETRaN",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5842,label:"URAMITA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5002,label:"ABEJORRAL",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5021,label:"ALEJANDRÍA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5055,label:"ARGELIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5148,label:"CARMEN DE VIBORAL",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5197,label:"COCORNA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5206,label:"CONCEPCIÓN",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5313,label:"GRANADA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5318,label:"GUARNE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5321,label:"GUATAPE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5376,label:"LA CEJA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5400,label:"LA UNIÓN",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5440,label:"MARINILLA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5483,label:"NARIÑO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5541,label:"PEÑOL",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5607,label:"RETIRO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5615,label:"RIONEGRO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5649,label:"SAN CARLOS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5652,label:"SAN FRANCISCO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5660,label:"SAN LUIS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5667,label:"SAN RAFAEL",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5674,label:"SAN VICENTE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5697,label:"SANTUARIO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5756,label:"SONSON",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5030,label:"AMAGa",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5034,label:"ANDES",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5036,label:"ANGELOPOLIS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5091,label:"BETANIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5093,label:"BETULIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5125,label:"CAICEDO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5145,label:"CARAMANTA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5101,label:"CIUDAD BOLÍVAR",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5209,label:"CONCORDIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5282,label:"FREDONIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5353,label:"HISPANIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5364,label:"JARDÍN",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5368,label:"JERICÓ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5390,label:"LA PINTADA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5467,label:"MONTEBELLO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5576,label:"PUEBLORRICO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5642,label:"SALGAR",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5679,label:"SANTA BaRBARA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5789,label:"TAMESIS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5792,label:"TARSO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5809,label:"TITIRIBÍ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5847,label:"URRAO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5856,label:"VALPARAISO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5861,label:"VENECIA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5045,label:"APARTADÓ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5051,label:"ARBOLETES",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5147,label:"CAREPA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5172,label:"CHIGORODÓ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5475,label:"MURINDÓ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5480,label:"MUTATA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5490,label:"NECOCLÍ",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5659,label:"SAN JUAN DE URABA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5665,label:"SAN PEDRO DE URABA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5837,label:"TURBO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5873,label:"VIGÍA DEL FUERTE",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5079,label:"BARBOSA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5088,label:"BELLO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5129,label:"CALDAS",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5212,label:"COPACABANA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5266,label:"ENVIGADO",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5308,label:"GIRARDOTA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5360,label:"ITAGUI",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5380,label:"LA ESTRELLA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5001,label:"MEDELLÍN",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:5631,label:"SABANETA",iddepto:5,nombredepto:"ANTIOQUIA"},
    {value:8001,label:"BARRANQUILLA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8296,label:"GALAPA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8433,label:"MALAMBO",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8573,label:"PUERTO COLOMBIA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8758,label:"SOLEDAD",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8137,label:"CAMPO DE LA CRUZ",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8141,label:"CANDELARIA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8421,label:"LURUACO",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8436,label:"MANATi",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8606,label:"REPELON",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8675,label:"SANTA LUCiA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8770,label:"SUAN",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8078,label:"BARANOA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8520,label:"PALMAR DE VARELA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8558,label:"POLONUEVO",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8560,label:"PONEDERA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8634,label:"Sabanagrande",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8638,label:"SABANALARGA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8685,label:"Santo Tomas",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8372,label:"JUAN DE ACOSTA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8549,label:"PIOJÓ",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8832,label:"TUBARA",iddepto:8,nombredepto:"ATLANTICO"},
    {value:8849,label:"USIACURi",iddepto:8,nombredepto:"ATLANTICO"},
    {value:11001,label:"BOGOTA D.C.",iddepto:11,nombredepto:"BOGOTA D.C."},
    {value:25183,label:"CHOCONTA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25426,label:"MACHETA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25436,label:"MANTA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25736,label:"SESQUILÉ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25772,label:"SUESCA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25807,label:"TIBIRITA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25873,label:"VILLAPINZÓN",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25001,label:"AGUA DE DIOS",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25307,label:"GIRARDOT",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25324,label:"GUATAQUÍ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25368,label:"JERUSALÉN",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25483,label:"NARIÑO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25488,label:"NILO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25612,label:"RICAURTE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25815,label:"TOCAIMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25148,label:"CAPARRAPÍ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25320,label:"GUADUAS",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25572,label:"PUERTO SALGAR",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25019,label:"ALBAN",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25398,label:"LA PEÑA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25402,label:"LA VEGA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25489,label:"NIMAIMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25491,label:"NOCAIMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25592,label:"QUEBRADANEGRA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25658,label:"SAN FRANCISCO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25718,label:"SASAIMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25777,label:"SUPATA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25851,label:"ÚTICA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25862,label:"VERGARA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25875,label:"VILLETA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25293,label:"GACHALA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25297,label:"GACHETA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25299,label:"GAMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25322,label:"GUASCA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25326,label:"GUATAVITA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25372,label:"JUNÍN",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25377,label:"LA CALERA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25839,label:"UBALA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25086,label:"BELTRAN",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25095,label:"BITUIMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25168,label:"CHAGUANÍ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25328,label:"GUAYABAL DE SIQUIMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25580,label:"PULI",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25662,label:"SAN JUAN DE RÍO SECO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25867,label:"VIANÍ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25438,label:"MEDINA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25530,label:"PARATEBUENO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25151,label:"CAQUEZA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25178,label:"CHIPAQUE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25181,label:"CHOACHÍ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25279,label:"FOMEQUE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25281,label:"FOSCA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25335,label:"GUAYABETAL",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25339,label:"GUTIÉRREZ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25594,label:"QUETAME",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25841,label:"UBAQUE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25845,label:"UNE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25258,label:"EL PEÑÓN",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25394,label:"LA PALMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25513,label:"PACHO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25518,label:"PAIME",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25653,label:"SAN CAYETANO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25823,label:"TOPAIPI",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25871,label:"VILLAGOMEZ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25885,label:"YACOPÍ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25126,label:"CAJICA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25175,label:"CHÍA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25200,label:"COGUA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25295,label:"GACHANCIPA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25486,label:"NEMOCoN",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25758,label:"SOPÓ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25785,label:"TABIO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25817,label:"TOCANCIPA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25899,label:"ZIPAQUIRA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25099,label:"BOJACA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25214,label:"COTA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25260,label:"EL ROSAL",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25269,label:"FACATATIVA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25286,label:"FUNZA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25430,label:"MADRID",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25473,label:"MOSQUERA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25769,label:"SUBACHOQUE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25799,label:"TENJO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25898,label:"ZIPACoN",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25740,label:"SIBATÉ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25754,label:"SOACHA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25053,label:"ARBELAEZ",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25120,label:"CABRERA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25290,label:"FUSAGASUGA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25312,label:"GRANADA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25524,label:"PANDI",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25535,label:"PASCA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25649,label:"SAN BERNARDO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25743,label:"SILVANIA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25805,label:"TIBACUY",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25506,label:"VENECIA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25035,label:"ANAPOIMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25040,label:"ANOLAIMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25599,label:"APULO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25123,label:"CACHIPAY",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25245,label:"EL COLEGIO",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25386,label:"LA MESA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25596,label:"QUIPILE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25645,label:"SAN ANTONIO DE TEQUENDAMA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25797,label:"TENA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25878,label:"VIOTA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25154,label:"CARMEN DE CARUPA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25224,label:"CUCUNUBA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25288,label:"FÚQUENE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25317,label:"GUACHETA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25407,label:"LENGUAZAQUE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25745,label:"SIMIJACA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25779,label:"SUSA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25781,label:"SUTATAUSA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25793,label:"TAUSA",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:25843,label:"UBATE",iddepto:25,nombredepto:"CUNDINAMARCA"},
    {value:47058,label:"ARIGUANÍ",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47170,label:"CHIBOLO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47460,label:"NUEVA GRANADA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47555,label:"PLATO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47660,label:"SABANAS DE SAN ANGEL",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47798,label:"TENERIFE",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47030,label:"ALGARROBO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47053,label:"ARACATACA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47189,label:"CIÉNAGA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47268,label:"EL RETEN",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47288,label:"FUNDACION",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47570,label:"PUEBLO VIEJO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47980,label:"ZONA BANANERA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47161,label:"CERRO SAN ANTONIO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47205,label:"CONCORDIA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47258,label:"EL PIÑON",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47541,label:"PEDRAZA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47551,label:"PIVIJAY",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47605,label:"REMOLINO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47675,label:"SALAMINA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47745,label:"SITIONUEVO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47960,label:"ZAPAYAN",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47001,label:"SANTA MARTA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47245,label:"EL BANCO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47318,label:"GUAMAL",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47545,label:"PIJIÑO DEL CARMEN",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47692,label:"SAN SEBASTIAN DE BUENAVISTA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47703,label:"SAN ZENON",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47707,label:"SANTA ANA",iddepto:47,nombredepto:"MAGDALENA"},
    {value:47720,label:"SANTA BARBARA DE PINTO",iddepto:47,nombredepto:"MAGDALENA"},
    {value:76036,label:"ANDALUCÍA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76111,label:"BUGA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76113,label:"BUGALAGRANDE",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76126,label:"CALIMA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76248,label:"EL CERRITO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76306,label:"GINEBRA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76318,label:"GUACARÍ",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76606,label:"RESTREPO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76616,label:"RIOFRIO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76670,label:"SAN PEDRO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76828,label:"TRUJILLO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76834,label:"TULUA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76890,label:"YOTOCO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76020,label:"ALCALa",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76041,label:"ANSERMANUEVO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76054,label:"ARGELIA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76100,label:"BOLÍVAR",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76147,label:"CARTAGO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76243,label:"EL AGUILA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76246,label:"EL CAIRO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76250,label:"EL DOVIO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76400,label:"LA UNIÓN",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76403,label:"LA VICTORIA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76497,label:"OBANDO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76622,label:"ROLDANILLO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76823,label:"TORO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76845,label:"ULLOA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76863,label:"VERSALLES",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76895,label:"ZARZAL",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76109,label:"BUENAVENTURA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76122,label:"CAICEDONIA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76736,label:"SEVILLA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76001,label:"CALI",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76130,label:"CANDELARIA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76233,label:"DAGUA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76275,label:"FLORIDA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76364,label:"JAMUNDÍ",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76377,label:"LA CUMBRE",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76520,label:"PALMIRA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76563,label:"PRADERA",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76869,label:"VIJES",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    {value:76892,label:"YUMBO",iddepto:76,nombredepto:"VALLE DEL CAUCA"},
    
];

